### ISSUE TITLE
Internal class problem

### ISSUE THREAD

**Issue by sinecode** [os6sense/xumlidot#42]
If I define a class inside another class, the methods defined in the outside class are displayed in the internal class.

For example:

    class MyClass
       class MyInternalClass; end

       def a_method; end

       def another_method; end
    end

I get the following dot diagram:

[uml.pdf](https://github.com/os6sense/xumlidot/files/7617974/uml.pdf)

I'm available to work on this issue because I really like this tool.

**Comment by os6sense** [comment]
Thanks for the PR, merged; sorry it's taken me so long to get around to this.

**Comment by os6sense** [comment]
Closing since PR merged.
